apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configuration
  namespace: elasticsearch
  labels: 
    app.kubernetes.io/name: logstash
    app.kubernetes.io/instance: logstash
    app.kubernetes.io/version: "7.10.1"
data: 
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
