apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-configuration
  namespace: elasticsearch
  labels:
    app.kubernetes.io/name: logstash
    app.kubernetes.io/instance: logstash
    app.kubernetes.io/version: "7.10.1"
data: 
  logstash.conf: |
    # all input will come from filebeat, no local logs
    input {
      beats {
        port => 5044
      }
    }
    filter {
    }
    output {
      elasticsearch {
        index => "logstash-%{[@metadata][beat]}"
        hosts => [ "${ES_HOSTS}" ]
        user => "${ES_USER}"
        password => "${ES_PASSWORD}"
        cacert => '/etc/logstash/certificates/root-ca.pem'
      }
    }