apiVersion: v1
kind: ServiceAccount
metadata:
  name: logstash
  namespace: elasticsearch
  labels:
    app.kubernetes.io/name: logstash
    app.kubernetes.io/instance: logstash
    app.kubernetes.io/version: "7.10.1"